- client/package-lock.json
- client/package.json
- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/Profile/Profile.jsx
- client/src/Components/SearchBar/SearchBar.jsx
- client/src/Redux/Store/store.js
- client/src/Views/LandingPage/Landing.jsx
- client/src/Views/SuperAdmin/SuperAdmin.jsx
- client/src/Views/Supervisor/Supervisor.jsx
- client/src/Views/Volunteer/Volunteer.jsx
- client/src/main.jsx
Creación de carpetas del front
> creacion de carpetas base

- client/src/App.jsx
- client/src/Components/Profile/Profile.jsx
- client/src/Redux/Reducer/reducer.js
- client/src/Redux/Store/store.js
- client/src/Views/LandingPage/Landing.jsx
- client/src/data.js
- client/vite.config.js
Agregué el componente profile con un sujeto de prueba y creé un archivo data.js para probar rutas y demás
> Componente Profile

- api/src/Models/Supervisor.js
> creacion modelo Supervisor/Lu

- api/src/Controllers/putSupervisor.js
- api/src/Routes/routes.js
ruta de putSupervisor y su controller
> ruta de putSupervisor y su controller

- api/index.js
- api/src/Controllers/getCompanionShift.js
- api/src/Models/CompanionShift.js
- api/src/Routes/routes.js
- api/src/db.js
> Db companion shift/lu

- api/src/Controllers/getCompanionShift.js
- api/src/Controllers/getSupervisorShift.js
correcion de HS, termina en 24
> correcionGetCompanionShift y getSupervisorShift/Lu

- api/src/Controllers/getCompanionShift.js
- api/src/Controllers/getSupervisorShift.js
Correccion formato hs tablas turnos /lu
> Correccion formato hs tablas turnos /lu

- api/index.js
- api/src/Controllers/getBothRoles.js
- api/src/Routes/routes.js
> Ruta para traer cualquier tipo de usuario de la bd

- api/src/Controllers/getBothRoles.js
un fix en la forma de retornar informacion
> fix en ruta

- api/src/Controllers/getBothRoles.js
- api/src/Routes/routes.js
Se agrega middleware para poder usar metodo post y enviar cosas por body
requiere email y password
> Fix ruta getBothRoles

- api/src/Controllers/getBothRoles.js
- client/package-lock.json
funcionando correctamente tira errores correctamente si los datos estan mal
> Controlador arreglado

- client/src/Redux/Actions/postPutActions.js
> alert de que creaste bien el usuario

- client/src/Components/LoginForm/LoginForm.jsx
Simplemente corregí la ruta que tenía /Chiringuito por /${id} para que sea dinámica y funcional
> Fixed Routes LoginForm

- api/src/Controllers/getCompanionByIdShift.js
- api/src/Routes/routes.js
- api/src/db.js
> getCompanionByIDShift

- client/src/Components/Perfiles/Companion/Companion.jsx
- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/CreateUser.jsx
- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
Los perfiles Companion y Supervisor se renderizan con la informacion que se suben desde register! Funciona
> Companion and Supervisor profile

- api/src/Controllers/Companion/getCompanionShift.js
> Coreccion hs

- api/src/Controllers/Supervisor/getSupervisorCharge.js
- api/src/Controllers/Supervisor/postSupervisorCharge.js
- api/src/Routes/routes.js
- api/src/db.js
Ruta para asignar companion a supervisor/lu
> Ruta para asignar companion a supervisor/lu

- client/src/App.jsx
- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
> supervisor responsive

- api/index.js
- api/src/Controllers/Companion/getCompanionShift.js
- api/src/Controllers/Supervisor/getSupervisorShift.js
Coreccion shift para que se seteen una sola vez
> Coreccion shift para que se seteen una sola vez

- api/index.js
- api/src/db.js
- client/package-lock.json
- client/package.json
- client/src/App.jsx
- client/src/Redux/Actions/postPutActions.js
- client/src/Redux/Actions/viewActions.js
- client/src/Views/Register/registerComponents/TimeZoneSelect.jsx
> Cambios deploy1/lu

- api/src/Routes/routes.js
requiereSuperAdmin para asignar supervisor
> requiereSuperAdmin para asignar supervisor

- api/src/db.js
> Deploy Changes

- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
- client/src/Views/Register/Register.jsx
> pequeños retoques

- client/src/App.jsx
- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
- client/src/Components/PopOut/PopOut.jsx
- client/src/Components/PopOut/PopOut.module.css
- client/src/Views/PanelSupervision/PanelSupervision.jsx
- client/src/Views/PanelSupervision/PanelSupervisorHelpers.jsx
Agregado Panel de Supervisión. Para acceder ir a la ruta "/panel-supervision" o clickear el botón que está en el perfil de los supervisores "PANEL DE SUPERVISION".
Ya esta todo funcional.
Solamente quedan algunos fixes pero necesito nuevas rutas o alguna otra solucion para ellos. Nada grave.
Gracias Charly por el PopOut :D
> Pedro/Panel Supervision

- client/src/Views/PanelSupervision/PanelSupervision.jsx
Arreglado problemas de turnos en Panel...
> Fixed stuff

- client/src/App.jsx
- client/src/Components/Cards/CompanionsAtCharge.jsx
- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
- client/src/Redux/Actions/viewActions.js
Card Companions at Charge conexión con back
> Card Companions at Charge conexión con back

- api/src/Controllers/Companion/getOneCompanion.js
- api/src/Controllers/Supervisor/getOneSupervisor.js
> Get one con turno

- api/src/Controllers/Companion/getCompanion.js
- api/src/Controllers/Supervisor/getSupervisor.js
Get Supervisor y Get companion con turnos
> Get Supervisor y Get companion con turnos

- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/GeneralSettings.jsx
Solo cambié el estilo de las letras de la configuracion general del Super Admin
> Fixed Typhografy Supervisor

- client/src/Components/Cards/CompanionsAtCharge.jsx
- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/AssignSupervisor.jsx
> Alertas Assign Supervisor

- client/src/Components/Cards/Cards.jsx
- client/src/Components/Cards/CompanionsAtCharge.jsx
ruta View Profile en personas a cargo
> ruta View Profile en personas a cargo

- client/src/Redux/Actions/postPutActions.js
Arreglado problemita con la sesion en el register/primer login 😎
> Fixed problema con la sesion en el primer login/register

- client/src/Components/Perfiles/SuperAdmin/SuperAdmin.jsx
- client/src/Components/Perfiles/SuperAdmin/SuperAdminDatos.jsx
solo 1 archivo nuevo y una linea modificada en duperadmin, no deveria generar conflicto
> perfil del super admin

- api/src/Controllers/Companion/getCompanion.js
- api/src/Controllers/Companion/getOneCompanion.js
- api/src/Controllers/Companion/postAssignCompanionShift.js
- api/src/Controllers/Companion/putCompanion.js
- api/src/Controllers/Supervisor/getOneSupervisor.js
- api/src/Controllers/Supervisor/getSupervisor.js
- api/src/Controllers/Supervisor/postAssignSupervisorShift.js
- api/src/Controllers/Supervisor/putSupervisor.js
- api/src/Controllers/Supervisor/putSupervisorCharge.js
Controladores actualizados para devolver la zona horaria del usuario
> Actualizacion en los puts

- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/UsersViewEdit.jsx
Columna cuenta activa en tabla del superAdm
> Cuenta activa

- api/src/Controllers/Companion/putCompanion.js
- api/src/Controllers/Supervisor/putSupervisor.js
Correccion put is active, si esta en null o undefined setea en true
> Correccion put

- client/src/Components/Perfiles/Companion/Companion.jsx
Permite que el acompañante edite sus datos personales desde su perfil.
> editar acompanante

- api/index.js
- client/src/Components/Calendary/CalendarSuperAdmin/CalendarSuperAdmin.jsx
- client/src/Components/Perfiles/Companion/Companion.jsx
- client/src/Components/Perfiles/SuperAdmin/SuperAdminDatos.jsx
- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
Correccion de bugs al mostrar la tarjeta de perfiles luego de llenar los datos.
> correcion bugs perfiles

- api/src/Controllers/Companion/postCompanion.js
- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/Perfiles/SuperAdmin/SuperAdminDatos.jsx
- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/UsersViewEdit.jsx
Nueva tarjeta perfil SuperAdmin
> perfil SuperAdmin

- client/src/Components/Calendary/CalendarCompanion/CalendarCompanionPopOut.jsx
- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
> Boton panel de supervision

- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/UsersViewEdit.jsx
- client/src/Components/VentanaLogin/EditForm.jsx
- client/src/Components/VentanaLogin/ModalEdit.jsx
Mañana conecto con el back y listo! DIOS 🤯
> EditInfo FUNCIONAAAAA

- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/UsersViewEdit.jsx
- client/src/Components/VentanaLogin/EditForm.jsx
Falta modificar funcionalidades (Back y front)
> Fix Edit Form

- client/src/Components/Perfiles/Companion/Companion.jsx
- client/src/Components/Perfiles/SuperAdmin/SuperAdminDatos.jsx
- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
Loader cargado y borrado de lineas comentadas (No cambié funcionalidad)
> Fixed Profiles

- client/src/Components/Calendary/CalendarCompanion/CalendarCompanion.jsx
- client/src/Components/Calendary/CalendarCompanion/CalendarCompanionPopOut.jsx
- client/src/Components/Perfiles/Companion/Companion.jsx
- client/src/Redux/Actions/postPutActions.js
> Cambios alertas companion

- client/src/Components/Cards/Cards.jsx
- client/src/Components/Cards/CompanionsAtCharge.jsx
- client/src/Components/Perfiles/Companion/Companion.jsx
- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
CSS a las tarjetas de personas a cargo (que estaban grises)
CSS al perfil del supervisor (que los botones no cabian en la pantalla)
> tarjetas personas a cargo

- api/src/Controllers/Companion/deleteCompanionShift.js
- api/src/Controllers/Companion/getAllCompanionsPerShift.js
- api/src/Controllers/Supervisor/getAllSupervisorsPerShift.js
> cambios controllers

- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/UsersViewEdit.jsx
La tabla del superadmin se auto ordena con los usuarios activos primero
> datatable sort active

- client/src/Components/Cards/Cards.jsx
- client/src/Components/Cards/CompanionsAtCharge.jsx
No es responsive, hay que terminarlo pero yo no tengo idea jeje
> Fixed cards companions at charge

- api/src/Controllers/Nodemailer/htmlMails/MailCreatedAccount.js
- client/src/Components/LoginForm/PasswordRecovery.jsx
- client/src/Redux/Actions/viewActions.js
> step de recuperar contraseña y estilos a los mails

- client/src/App.jsx
- client/src/Components/Cards/CompanionsAtCharge.jsx
- client/src/Components/Perfiles/Companion/Companion.jsx
- client/src/Views/Register/EditInfo.jsx
ajustes en la actualizacion de Redux y correccion de un error al calcular la hora local de cada usuario
> local time and update redux

- api/src/Controllers/Supervisor/getAllSupervisorsPerShift.js
- client/src/App.jsx
- client/src/Components/Calendary/CalendarSuperAdmin/CalendarSuperAdmin.jsx
- client/src/Components/Calendary/CalendarSuperAdmin/CalendarSuperAdminPopOut.jsx
- client/src/Redux/Reducer/authReducer.js
> SuperAdm Calendar

- api/src/Controllers/Supervisor/postAssignSupervisorShift.js
- client/src/Components/Calendary/CalendarSuperAdmin/CalendarSuperAdmin.jsx
- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/Perfiles/SuperAdmin/SuperAdmin.jsx
- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/AssignSupervisor.jsx
calendar supervisor y botones en el perfil superAdmin
> calendar supervisor

- client/src/Components/VentanaLogin/EditForm.jsx
- client/src/Components/VentanaLogin/ModalEdit.jsx
- client/src/Views/Register/Register.jsx
- client/src/Views/Register/registerComponents/Select.jsx
- client/src/Views/Register/registerComponents/TimeZoneSelect.jsx
> Fix edit form superAdmin

- client/src/Components/Perfiles/SuperAdmin/SuperAdminDatos.jsx
- client/src/Components/Perfiles/SuperAdmin/SuperAdminStyle.js
> super admin perfil

- api/src/Controllers/Companion/postCompanion.js
- api/src/Controllers/Supervisor/postSupervisor.js
- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/CreateUser.jsx
- client/src/Redux/Actions/postPutActions.js
password autogenerada si no se llena la contraseña desde el front
> fix ruta post

- client/src/Components/NavBar/NavBar.jsx
- client/src/Components/Perfiles/Companion/CompanionProfile.js
Quité el fondo del perfil y agregué una sombra a la NavBar para separarla del resto de la app!
> Fix NavBar and Companion Profile

- api/src/Controllers/Companion/getAllCompanionsPerShift.js
- client/src/App.jsx
- client/src/Components/Calendary/CalendarCompanion/CalendarCompanion.jsx
- client/src/Components/Calendary/CalendarCompanion/CalendarCompanionPopOut.jsx
- client/src/Components/Calendary/CalendarCompanionSA/CalendarCompanionSA.css
- client/src/Components/Calendary/CalendarCompanionSA/CalendarCompanionSA.jsx
- client/src/Components/Calendary/CalendarCompanionSA/CalendarCompanionSAPopOut.jsx
- client/src/Components/Calendary/CalendarCompanionSA/CalendarCompanionSAPopOut.module.css
- client/src/Components/Calendary/CalendarSuperAdmin/CalendarSuperAdmin.jsx
- client/src/Components/NavBar/NavBar.jsx
- client/src/Redux/Actions/postPutActions.js
- client/src/Redux/Reducer/authReducer.js
- client/src/Redux/Reducer/viewReducer.js
> calendarios

- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/CreateUser.jsx
- client/src/Views/Register/Register.jsx
Se agrega un switch para la contraseña, dandole la posibilidad al SuperAdmin de decidir si enviar o no una contraseña. Además agregué un margen al formulario de registro para que no esté tan pegado a la NavBar
> Fix create user and register

- client/src/Components/Perfiles/Supervisor/Supervisor.jsx
- client/src/Components/Perfiles/Supervisor/SupervisorStyles.js
Falta definir lo del calendario y las vistas del Supervisor, pero ya está terminado el perfil
> Supervisor Profile

- client/src/Components/ViewProfile/ViewProfile.jsx
> back button to profile others

- client/src/Components/Calendary/CalendarCompanion/CalendarCompanion.jsx
- client/src/Components/Calendary/CalendarCompanionSA/CalendarCompanionSA.jsx
- client/src/Components/Calendary/CalendarCompanionSA/CalendarCompanionSAPopOut.jsx
- client/src/Components/Calendary/CalendarSuperAdmin/CalendarSuperAdmin.jsx
arreglo bug bucle infito calendarios
> arreglo bug bucle infito calendarios

- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/CreateUser.jsx
- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/CsvImportExport.jsx
- client/src/Components/Perfiles/SuperAdmin/superAdminComponents/UsersViewEdit.jsx
Limpieza del perfil de superadmin, renombrado de acompañantes, borrado de importaciones no usadas.
> cleanup superadmin

- client/src/Components/Modals/EditForm.jsx
Ajuste del alto del formulario de edit user, adicion del boton de cancelar y limpieza del codigo.
> edit user form styles
